[workspace]
resolver = "2"
members = [
    "crates/graphnet-core",
    "crates/graphnet-demo"
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["v4", "serde"] }
